name: Dependency Update and Security Scan

on:
  schedule:
    - cron: '0 2 * * 1' # Every Monday at 2 AM
  workflow_dispatch:

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Update frontend dependencies
      run: |
        npx npm-check-updates -u
        npm install
        npm audit fix
        
    - name: Update backend dependencies
      run: |
        cd backend
        npx npm-check-updates -u
        npm install
        npm audit fix
        
    - name: Run tests after updates
      run: |
        npm test
        cd backend && npm test
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Weekly Dependency Updates'
        body: |
          Automated dependency updates:
          - Frontend dependencies updated
          - Backend dependencies updated
          - Security vulnerabilities fixed
          - All tests passing
        branch: dependency-updates
        delete-branch: true

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Snyk security scan
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
        
    - name: Upload Snyk results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif